version: "2"

services:
  script:
    build: ./src
    volumes:
      - ./src:/src
    networks:
      - "172.17.0.1" # so that the python script can POST data to localhost on host machine

  redis:
    image: redis
    ports:
      - "6379"

  mynodeapp:
    build: ./node_app
    ports:
      - "3000:3000"
    links:
      - redis
