version: "2"

services:
  script:
    build: ./src
    volumes:
      - ./src:/src
    networks:
      - mynetwork

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  mynodeapp:
    build: ./node_app
    ports:
      - "3000:3000"
    networks:
			- mynetwork
		depends_on:
			- redis

networks:
	mynetwork:
 		driver: bridge
